from . import medicine
from . import laboratory_test
from . import laboratory_test_order
from . import medical_test
from . import medical_test_order
from . import patient
from . import patient_appointment
from . import patient_appointment_reason
from . import patient_background
from . import patient_diagnosis
from . import patient_family
from . import patient_prescription
from . import pharmacological_treatment
