{
    "name": "Doctor's Office Management",
    "summary": """
        Doctor's Office Management
    """,
    "description": "",
    "author": "javibits <javibits.io@gmail.com>",
    "website": "",
    "category": "Services/Health",
    "version": "0.1",
    "depends": ["base", "contacts"],
    "data": [
        "security/dom_groups.xml",
        "security/ir.model.access.csv",
        "data/dom_sequence.xml",
        "views/medicine.xml",
        "views/patient.xml",
        "views/patient_appointment.xml",
        "views/patient_appointment_reason.xml",
        "views/patient_background_item.xml",
        "views/patient_diagnosis.xml",
        "views/patient_family.xml",
        "views/patient_prescription.xml",
        "views/pharmacological_treatment.xml",
        "views/menus.xml",
    ],
    "demo": [],
    "license": "AGPL-3",
    "application": True,
}
